#include <core/linux.h>
#include <errno.h>
#include <core/linux_syscall.h>

const char *linux_errno_cstr(usz errno_val)
{
    switch (errno_val)
    {
    case 0:                 return "SUCCESS";
    case EPERM:             return "EPERM";
    case ENOENT:            return "ENOENT";
    case ESRCH:             return "ESRCH";
    case EINTR:             return "EINTR";
    case EIO:               return "EIO";
    case ENXIO:             return "ENXIO";
    case E2BIG:             return "E2BIG";
    case ENOEXEC:           return "ENOEXEC";
    case EBADF:             return "EBADF";
    case ECHILD:            return "ECHILD";
    case EAGAIN:            return "EAGAIN";
    case ENOMEM:            return "ENOMEM";
    case EACCES:            return "EACCES";
    case EFAULT:            return "EFAULT";
    case ENOTBLK:           return "ENOTBLK";
    case EBUSY:             return "EBUSY";
    case EEXIST:            return "EEXIST";
    case EXDEV:             return "EXDEV";
    case ENODEV:            return "ENODEV";
    case ENOTDIR:           return "ENOTDIR";
    case EISDIR:            return "EISDIR";
    case EINVAL:            return "EINVAL";
    case ENFILE:            return "ENFILE";
    case EMFILE:            return "EMFILE";
    case ENOTTY:            return "ENOTTY";
    case ETXTBSY:           return "ETXTBSY";
    case EFBIG:             return "EFBIG";
    case ENOSPC:            return "ENOSPC";
    case ESPIPE:            return "ESPIPE";
    case EROFS:             return "EROFS";
    case EMLINK:            return "EMLINK";
    case EPIPE:             return "EPIPE";
    case EDOM:              return "EDOM";
    case ERANGE:            return "ERANGE";
    case EDEADLK:           return "EDEADLK";
    case ENAMETOOLONG:      return "ENAMETOOLONG";
    case ENOLCK:            return "ENOLCK";
    case ENOSYS:            return "ENOSYS";
    case ENOTEMPTY:         return "ENOTEMPTY";
    case ELOOP:             return "ELOOP";
    case ENOMSG:            return "ENOMSG";
    case EIDRM:             return "EIDRM";
    case ECHRNG:            return "ECHRNG";
    case EL2NSYNC:          return "EL2NSYNC";
    case EL3HLT:            return "EL3HLT";
    case EL3RST:            return "EL3RST";
    case ELNRNG:            return "ELNRNG";
    case EUNATCH:           return "EUNATCH";
    case ENOCSI:            return "ENOCSI";
    case EL2HLT:            return "EL2HLT";
    case EBADE:             return "EBADE";
    case EBADR:             return "EBADR";
    case EXFULL:            return "EXFULL";
    case ENOANO:            return "ENOANO";
    case EBADRQC:           return "EBADRQC";
    case EBADSLT:           return "EBADSLT";
    case EBFONT:            return "EBFONT";
    case ENOSTR:            return "ENOSTR";
    case ENODATA:           return "ENODATA";
    case ETIME:             return "ETIME";
    case ENOSR:             return "ENOSR";
    case ENONET:            return "ENONET";
    case ENOPKG:            return "ENOPKG";
    case EREMOTE:           return "EREMOTE";
    case ENOLINK:           return "ENOLINK";
    case EADV:              return "EADV";
    case ESRMNT:            return "ESRMNT";
    case ECOMM:             return "ECOMM";
    case EPROTO:            return "EPROTO";
    case EMULTIHOP:         return "EMULTIHOP";
    case EDOTDOT:           return "EDOTDOT";
    case EBADMSG:           return "EBADMSG";
    case EOVERFLOW:         return "EOVERFLOW";
    case ENOTUNIQ:          return "ENOTUNIQ";
    case EBADFD:            return "EBADFD";
    case EREMCHG:           return "EREMCHG";
    case ELIBACC:           return "ELIBACC";
    case ELIBBAD:           return "ELIBBAD";
    case ELIBSCN:           return "ELIBSCN";
    case ELIBMAX:           return "ELIBMAX";
    case ELIBEXEC:          return "ELIBEXEC";
    case EILSEQ:            return "EILSEQ";
    case ERESTART:          return "ERESTART";
    case ESTRPIPE:          return "ESTRPIPE";
    case EUSERS:            return "EUSERS";
    case ENOTSOCK:          return "ENOTSOCK";
    case EDESTADDRREQ:      return "EDESTADDRREQ";
    case EMSGSIZE:          return "EMSGSIZE";
    case EPROTOTYPE:        return "EPROTOTYPE";
    case ENOPROTOOPT:       return "ENOPROTOOPT";
    case EPROTONOSUPPORT:   return "EPROTONOSUPPORT";
    case ESOCKTNOSUPPORT:   return "ESOCKTNOSUPPORT";
    case EOPNOTSUPP:        return "EOPNOTSUPP";
    case EPFNOSUPPORT:      return "EPFNOSUPPORT";
    case EAFNOSUPPORT:      return "EAFNOSUPPORT";
    case EADDRINUSE:        return "EADDRINUSE";
    case EADDRNOTAVAIL:     return "EADDRNOTAVAIL";
    case ENETDOWN:          return "ENETDOWN";
    case ENETUNREACH:       return "ENETUNREACH";
    case ENETRESET:         return "ENETRESET";
    case ECONNABORTED:      return "ECONNABORTED";
    case ECONNRESET:        return "ECONNRESET";
    case ENOBUFS:           return "ENOBUFS";
    case EISCONN:           return "EISCONN";
    case ENOTCONN:          return "ENOTCONN";
    case ESHUTDOWN:         return "ESHUTDOWN";
    case ETOOMANYREFS:      return "ETOOMANYREFS";
    case ETIMEDOUT:         return "ETIMEDOUT";
    case ECONNREFUSED:      return "ECONNREFUSED";
    case EHOSTDOWN:         return "EHOSTDOWN";
    case EHOSTUNREACH:      return "EHOSTUNREACH";
    case EALREADY:          return "EALREADY";
    case EINPROGRESS:       return "EINPROGRESS";
    case ESTALE:            return "ESTALE";
    case EUCLEAN:           return "EUCLEAN";
    case ENOTNAM:           return "ENOTNAM";
    case ENAVAIL:           return "ENAVAIL";
    case EISNAM:            return "EISNAM";
    case EREMOTEIO:         return "EREMOTEIO";
    case EDQUOT:            return "EDQUOT";
    case ENOMEDIUM:         return "ENOMEDIUM";
    case EMEDIUMTYPE:       return "EMEDIUMTYPE";
    case ECANCELED:         return "ECANCELED";
    case ENOKEY:            return "ENOKEY";
    case EKEYEXPIRED:       return "EKEYEXPIRED";
    case EKEYREVOKED:       return "EKEYREVOKED";
    case EKEYREJECTED:      return "EKEYREJECTED";
    case EOWNERDEAD:        return "EOWNERDEAD";
    case ENOTRECOVERABLE:   return "ENOTRECOVERABLE";
    case ERFKILL:           return "ERFKILL";
    case EHWPOISON:         return "EHWPOISON";
    default:                return "UNKNOWN_ERRNO";
    };
}


const char *linux_signal_str(int sig_num)
{
    switch (sig_num)
    {
    case 0:                     return "NONE";
    case LINUX_SIGHUP:          return "LINUX_SIGHUP";
    case LINUX_SIGINT:          return "LINUX_SIGINT";
    case LINUX_SIGQUIT:         return "LINUX_SIGQUIT";
    case LINUX_SIGILL:          return "LINUX_SIGILL";
    case LINUX_SIGTRAP:         return "LINUX_SIGTRAP";
    case LINUX_SIGABRT:         return "LINUX_SIGABRT";
    case LINUX_SIGBUS:          return "LINUX_SIGBUS";
    case LINUX_SIGFPE:          return "LINUX_SIGFPE";
    case LINUX_SIGKILL:         return "LINUX_SIGKILL";
    case LINUX_SIGUSR1:         return "LINUX_SIGUSR1";
    case LINUX_SIGSEGV:         return "LINUX_SIGSEGV";
    case LINUX_SIGUSR2:         return "LINUX_SIGUSR2";
    case LINUX_SIGPIPE:         return "LINUX_SIGPIPE";
    case LINUX_SIGALRM:         return "LINUX_SIGALRM";
    case LINUX_SIGTERM:         return "LINUX_SIGTERM";
    case LINUX_SIGSTKFLT:       return "LINUX_SIGSTKFLT";
    case LINUX_SIGCHLD:         return "LINUX_SIGCHLD";
    case LINUX_SIGCONT:         return "LINUX_SIGCONT";
    case LINUX_SIGSTOP:         return "LINUX_SIGSTOP";
    case LINUX_SIGTSTP:         return "LINUX_SIGTSTP";
    case LINUX_SIGTTIN:         return "LINUX_SIGTTIN";
    case LINUX_SIGTTOU:         return "LINUX_SIGTTOU";
    case LINUX_SIGURG:          return "LINUX_SIGURG";
    case LINUX_SIGXCPU:         return "LINUX_SIGXCPU";
    case LINUX_SIGXFSZ:         return "LINUX_SIGXFSZ";
    case LINUX_SIGVTALRM:       return "LINUX_SIGVTALRM";
    case LINUX_SIGPROF:         return "LINUX_SIGPROF";
    case LINUX_SIGWINCH:        return "LINUX_SIGWINCH";
    case LINUX_SIGIO:           return "LINUX_SIGIO";
    case LINUX_SIGPWR:          return "LINUX_SIGPWR";
    case LINUX_SIGSYS:          return "LINUX_SIGSYS";
    case LINUX_SIGRTMIN + 0:    return "LINUX_SIGRTMIN+0";
    case LINUX_SIGRTMIN + 1:    return "LINUX_SIGRTMIN+1";
    case LINUX_SIGRTMIN + 2:    return "LINUX_SIGRTMIN+2";
    case LINUX_SIGRTMIN + 3:    return "LINUX_SIGRTMIN+3";
    case LINUX_SIGRTMIN + 4:    return "LINUX_SIGRTMIN+4";
    case LINUX_SIGRTMIN + 5:    return "LINUX_SIGRTMIN+5";
    case LINUX_SIGRTMIN + 6:    return "LINUX_SIGRTMIN+6";
    case LINUX_SIGRTMIN + 7:    return "LINUX_SIGRTMIN+7";
    case LINUX_SIGRTMIN + 8:    return "LINUX_SIGRTMIN+8";
    case LINUX_SIGRTMIN + 9:    return "LINUX_SIGRTMIN+9";
    case LINUX_SIGRTMIN + 10:   return "LINUX_SIGRTMIN+10";
    case LINUX_SIGRTMIN + 11:   return "LINUX_SIGRTMIN+11";
    case LINUX_SIGRTMIN + 12:   return "LINUX_SIGRTMIN+12";
    case LINUX_SIGRTMIN + 13:   return "LINUX_SIGRTMIN+13";
    case LINUX_SIGRTMIN + 14:   return "LINUX_SIGRTMIN+14";
    case LINUX_SIGRTMIN + 15:   return "LINUX_SIGRTMIN+15";
    case LINUX_SIGRTMIN + 16:   return "LINUX_SIGRTMIN+16";
    case LINUX_SIGRTMIN + 17:   return "LINUX_SIGRTMIN+17";
    case LINUX_SIGRTMIN + 18:   return "LINUX_SIGRTMIN+18";
    case LINUX_SIGRTMIN + 19:   return "LINUX_SIGRTMIN+19";
    case LINUX_SIGRTMIN + 20:   return "LINUX_SIGRTMIN+20";
    case LINUX_SIGRTMIN + 21:   return "LINUX_SIGRTMIN+21";
    case LINUX_SIGRTMIN + 22:   return "LINUX_SIGRTMIN+22";
    case LINUX_SIGRTMIN + 23:   return "LINUX_SIGRTMIN+23";
    case LINUX_SIGRTMIN + 24:   return "LINUX_SIGRTMIN+24";
    case LINUX_SIGRTMIN + 25:   return "LINUX_SIGRTMIN+25";
    case LINUX_SIGRTMIN + 26:   return "LINUX_SIGRTMIN+26";
    case LINUX_SIGRTMIN + 27:   return "LINUX_SIGRTMIN+27";
    case LINUX_SIGRTMIN + 28:   return "LINUX_SIGRTMIN+28";
    case LINUX_SIGRTMIN + 29:   return "LINUX_SIGRTMIN+29";
    case LINUX_SIGRTMIN + 30:   return "LINUX_SIGRTMIN+30";
    case LINUX_SIGRTMIN + 31:   return "LINUX_SIGRTMIN+31";
    default:                    return "UNKNOWN_SIGNAL";
    }
}
